db:
  user: # change it
  password: #change it
  host: #change it
  schema: gotocloud # 数据库名，默认不用修改
jwt:
  security: thisisunsafeuntilyouchangit
  realm: GOTOCLOUD
  idkey: id
kind:
  - admin # 管理员
  - pm    # 项目经理
  - dev   # 开发
  - qa    # 质量
  - op    # 运维
agent:
  image: gotocloud.cn/image:latest
server:
  host: http://localhost:18081 # gotocloud服务地址，可被agent访问，注意：这个host作用于agent通信，非web站点后端服务地址