db:
  user: 数据库用户名
  password: 数据库密码
  host: 主机地址(127.0.0.1)
  schema: gotocloud # 数据库名，默认不用修改
jwt:
  security: thisisunsafeuntilyouchangit
  realm: GOTOCLOUD
  idkey: id
kind:
  - admin # 管理员
  - pm    # 项目经理
  - dev   # 开发
  - qa    # 质量
  - op    # 运维