db:
  user: # change it
  password: #change it
  host: #change it
  schema: gotocloud # 数据库名，默认不用修改
jwt:
  security: thisisunsafeuntilyouchangit
  realm: GOTOCLOUD
  idkey: id
kind:
  - admin # 管理员
  - pm    # 项目经理
  - dev   # 开发
  - qa    # 质量
  - op    # 运维
builder:
  kaniko: go-to-cloud-docker.pkg.coding.net/devops/kaniko/executor:v1.9.1-debug