// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/configure/artifact/testing": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "制品仓库配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/artifact.Testing"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/coderepo": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "代码仓库配置",
                "tags": [
                    "Configure"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/coderepo/:id": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "代码仓库配置",
                "tags": [
                    "Configure"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/coderepo/bind": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "代码仓库配置",
                "tags": [
                    "Configure"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "代码仓库配置",
                "tags": [
                    "Configure"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/coderepo/testing": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "代码仓库配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scm.Testing"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "description": "Login Model",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/projects/list": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "查看项目信息",
                "tags": [
                    "Projects"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/user/info": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "查看用户信息",
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/user/logout": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "注销登录",
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "artifact.Testing": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isSecurity": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "models.LoginModel": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "scm.Testing": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isPublic": {
                    "type": "boolean"
                },
                "origin": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
