name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login Registry
      env:
        REGISTRY_USERNAME: ${{secret.REGISTRY_USERNAME}}
        REGISTRY_PASSWORD: ${{secret.REGISTRY_PASSWORD}}
      run: |
        echo "${REGISTRY_PASSWORD}" | docker login -u ${REGISTRY_USERNAME} go-to-cloud-docker.pkg.coding.net --password-stdin
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --output "type=image,push=true" --file Dockerfile --tag gtc:$(date +%s)
